### ISSUE TITLE
Can't install package from Dockerfile

### ISSUE THREAD

**Issue by Soullivaneuh** [gentoo/gentoo-docker-images#35]
If you try something like this:

``` Dockerfile
FROM gentoo/stage3-amd64

RUN emerge -qv www-servers/apache
```

You will get: 

``` bash
!!! Section 'x-portage' in repos.conf has location attribute set to nonexistent directory: '/usr/portage'
!!! Section 'gentoo' in repos.conf has location attribute set to nonexistent directory: '/usr/portage'
!!! Invalid Repository Location (not a dir): '/usr/portage'


!!! /etc/portage/make.profile is not a symlink and will probably prevent most merges.
!!! It should point into a profile within /usr/portage/profiles/
!!! (You can safely ignore this message when syncing. It's harmless.)


!!! Your current profile is invalid. If you have just changed your profile
!!! configuration, you should revert back to the previous configuration.
!!! Allowed actions are limited to --help, --info, --search, --sync, and
!!! --version.
```

This is because of the separation of portage structure on another image. On running image it's working.

Here is my `docker-compose.yml` file:

```yaml
portage:
  image: gentoo/portage

nx-default:
  build: docker/gentoo
  hostname: nx-default.nexylan.net
  volumes_from:
    - portage
  links:
    - influxdb
```

I'm not an expert but why separating Portage? Because of this, we can't install package on image building.

Regards.
