### ISSUE TITLE
Cannot create container for service portage: No command specified

### ISSUE THREAD

**Issue by Soullivaneuh** [gentoo/gentoo-docker-images#42]
Since the last docker pull with the following `docker-compose.yml` extract:

```yaml
  portage:
    image: gentoo/portage

  nx-default:
    build: docker/gentoo
    hostname: nx-default.nexylan.net
    volumes_from:
      - portage
    depends_on:
      - influxdb
```

And I have the following error:

```
ERROR: for portage  Cannot create container for service portage: No command specified
```

I tried to add `command: /bin/true` but I have the following error:

```
ERROR: for portage  Cannot start service portage: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/bin/true\": stat /bin/true: no such file or directory"
```

Any idea? This was working without command before the last pull.
